<?xml version="1.0"?>
<package format="2">
  <name>iiwa_udp_communication</name>
  <version>0.1.0</version>
  <description>Package for sending udp commands a kuka iiwa robot</description>

  <maintainer email="b6218@algoritmi.uminho.pt">Paulo Vicente</maintainer>


  <!-- One license tag required, multiple allowed, one license per tag -->
  <!-- Commonly used license strings: -->
  <!--   BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3 -->
  <license>TODO</license>


  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>rospy</build_depend>
  <build_export_depend>rospy</build_export_depend>
  <exec_depend>rospy</exec_depend>
</package>
